import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className=""></nav>
        {children}
        <div className="bg-blue-600 text-white height-500 p-8 font-sans flex justify-center items-center">
          <button className="bg-sky-600 hover:bg-sky-700 text-white font-bold py-2 px-4 rounded-xl transition-colors duration-300">
            Click Me
          </button>
          <button className="bg-sky-600 hover:bg-sky-700 text-white font-bold py-2 px-4 rounded-xl transition-colors duration-300">
            Click Me
          </button>
        </div>
      </body>
    </html>
  );
}
