// src/models/City.ts
import mongoose, { Schema, Document } from "mongoose";
import { CityContent } from "@/lib/ai/city.schema"; // Import the content schema type

// 1. Define the interface for our City document, including AI fields
export interface ICity extends Document {
  _id: string;
  name: string;
  continent: string;
  status?: "pending" | "ready" | "error";
  content?: CityContent | null;
  lastRefreshed?: Date | null;
  error?: string | null;
}

// 2. Create the Mongoose Schema
const CitySchema: Schema = new Schema(
  {
    _id: {
      type: String,
      required: [true, "Please provide a unique ID for the city."],
    },
    name: {
      type: String,
      required: [true, "Please provide a name for the city."],
      trim: true,
    },
    continent: {
      type: String,
      required: [true, "Please provide the continent for the city."],
      trim: true,
    },
    // AI fields
    status: {
      type: String,
      enum: ["pending", "ready", "error"],
      default: "pending",
      index: true,
    },
    content: {
      // structured JSON generated by the agent
      type: Schema.Types.Mixed,
      default: null,
    },
    lastRefreshed: { type: Date, default: null },
    error: { type: String, default: null },
  },
  { timestamps: true }
);

// 3. Create and export the Mongoose Model
export default mongoose.models.City ||
  mongoose.model<ICity>("City", CitySchema);
